description: Single GPU example job from GCR

target:
  service: aisc

environment:
  image: amlt-sing/pytorch-1.8.0
  setup:
  - git clone --branch v4.16.1  https://github.com/huggingface/transformers.git ~/transformers
  - pip install ~/transformers/
  - pip install datasets

code:
  local_dir: $CONFIG_DIR/example


jobs:
- name: gcr-example
  sku: G1
  mpi: False
  process_count_per_node: 0
  command:
  - python hello.py
  - python ~/transformers/examples/pytorch/language-modeling/run_clm.py --fp16 --model_name_or_path gpt2 --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --do_train --do_eval --output_dir $$AMLT_OUTPUT_DIR --per_device_train_batch_size 4
  sla_tier: Premium
  execution_mode: basic
  priority: medium
  azml_int: True
  submit_args:
    env:
      {NCCL_DEBUG: "INFO"}
